# Generated by Django 4.1.6 on 2023-02-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='costumer',
            new_name='custumer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='costumer',
            new_name='custumer',
        ),
    ]
