# Generated by Django 4.1.6 on 2023-02-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_costumer_order_custumer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custumer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='custumer',
            new_name='customer',
        ),
    ]
